import { NextResponse } from "next/server";
import { getSessionUser } from "../../../lib/auth";
import { checkRateLimit } from "../../../lib/rate-limit";

/* ────────────────────────────────────────────────────────────────
   AI decides EVERYTHING from minimal input.
   Kinetic AI then generates the COMPLETE final thumbnail —
   background + person + all text baked into one image.
   ──────────────────────────────────────────────────────────────── */

export async function POST(request) {
  try {
    const rateLimit = checkRateLimit(request, "plan", 30, 60 * 60 * 1000);
    if (!rateLimit.allowed) return NextResponse.json({ success: false, error: "Planning limit reached. Please try again later." }, { status: 429, headers: { "Retry-After": String(rateLimit.retryAfter) } });
    const user = await getSessionUser();
    if (!user) {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { videoTopic, brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode } = body;
    const creatorType = body.creatorType || user.creatorType || "education";
    if (typeof videoTopic !== "string" || videoTopic.trim().length === 0 || videoTopic.length > 8_000) {
      return NextResponse.json({ success: false, error: "Video topic must be between 1 and 8,000 characters." }, { status: 400 });
    }

    const apiKey = process.env.DEEPSEEK_API_KEY;

    /* ── Mock fallback (no key) — always skip to full plan so sandbox works end-to-end ── */
    if (!apiKey) {
      console.log("DeepSeek key missing — returning smart fallback plan");
      await new Promise(r => setTimeout(r, 1400));
      const plan = buildFallbackPlan({ videoTopic, brandColor, highlightColor, hasSubjectPhoto, poseMode }, true);
      return NextResponse.json({ success: true, needsMoreInfo: false, plan, isMock: true });
    }

    /* ── Live DeepSeek call ─────────────────────────────────────── */
    const subjectInstruction = hasSubjectPhoto
      ? `Multi-angle reference photo(s) (Front view, Left profile, Right profile) of the creator will be sent to the image model. Pose mode: "${poseMode}" — ${
          poseMode === "ai"
            ? "choose the most impactful pose (pointing up, shocked, excited, authoritative)"
            : "keep their exact pose from the reference photo(s)"
        }. Reconstruct their exact 3D facial likeness, skin tone, and features with 100% precision.`
      : "No subject photo. Image model will create a compelling Indian educator/presenter character.";

    const isSecondPass = videoTopic.includes("Additional details provided by creator:");

    let systemPrompt, userPrompt;

    if (!isSecondPass) {
      // Mandatory First Pass: Ask Questions
      systemPrompt = [
        "You are the world's sharpest YouTube thumbnail strategist, specialising in Indian education channels.",
        "A creator just described their video topic. Your ONLY job right now is to check if there are any EXTERNAL FACTS missing that you cannot possibly infer or invent — for example: a specific exam date, a university or board name, a course/subject code, or a specific person's name.",
        "CRITICAL RULES:",
        "- NEVER ask about what text or headline to use — YOU decide that based on the topic.",
        "- NEVER ask what topic, concept, or subject to focus on — it's already in the video topic.",
        "- NEVER ask about design, layout, style, emotions, colors, or any creative decision — YOU own all of that.",
        "- ONLY ask if a concrete external fact is genuinely missing AND would materially change the design (e.g. an exam date that needs to appear as a date callout).",
        "- If you can fully design the thumbnail from the given topic alone, return needsMoreInfo: false with 0 questions.",
        "- Maximum 1 question. Never more.",
        "If you do ask, provide 2–3 plausible preset options matching the context. Always include 'Other (please specify)' last.",
        "Respond ONLY with raw JSON — no markdown:",
        '{ "needsMoreInfo": true, "questions": [ { "question": "<specific factual question>", "options": ["<opt1>", "<opt2>", "Other (please specify)"] } ] }',
        "OR if no facts are missing:",
        '{ "needsMoreInfo": false }',
      ].join("\n");

      userPrompt = `VIDEO TOPIC: "${videoTopic}"\n\nDecide: is there any specific external fact (date, board name, code, etc.) missing that would materially change the thumbnail design? If yes, ask 1 question. If no, return needsMoreInfo: false immediately.`;
    } else {
      // Second Pass: Generate Full Plan
      systemPrompt = [
        "You are the world's #1 YouTube thumbnail strategist for Indian education and news channels.",
        "",
        "Given ONLY the video topic, additional details, and brand color, you decide ALL creative elements.",
        "The final image will be fully generated by Kinetic AI — text, person, background, everything in one shot.",
        "",
        "Use your own judgment to decide which overlay elements genuinely fit the content.",
        "Think: what would a smart, experienced creator actually put on this thumbnail?",
        "A revision/lecture video needs a punchy headline — not an alert card or date callout.",
        "An exam postponement needs an alert card, a date callout, and an urgent banner.",
        "A result video needs a success card and excitement. Match the energy to the topic naturally.",
        "",
        "SUBJECT POSE RULES (CRITICAL):",
        "- Design a high-impact, highly relevant pose for the subject.",
        "- Ensure the subject is making a clear hand gesture (such as pointing their index finger straight up, pointing at the camera, or pointing at the headlines).",
        "- Crucially, specify a physical prop related to the topic that the subject is holding or wearing (e.g., for fashion: a tailor's measuring tape around their neck or holding design blueprints; for exams: holding a printed notice page or circular; for motivation: holding a trophy or book; for finance: holding a stack of charts).",
        "- The pose description in the plan should look like: 'right index finger pointing straight up, confident smiling expression, wearing a tailor's measuring tape around their neck and holding design blueprints'",
        "",
        "CRITICAL RULE: DO NOT HALLUCINATE, INVENT, OR ASSUME ANY FACTS OR DATES.",
        "- You now have all the explicit info from the creator.",
        "- Only use the details they provided.",
        "- Return the full plan with needsMoreInfo: false.",
        "",
        "TEXT RULES:",
        "- Headline: SHORT and PUNCHY — max 2-3 words per line",
        "- Use HINGLISH where it genuinely fits the topic tone",
        "- accentColor: bright high-contrast against the brand color (usually #f5d800 yellow)",
        "",
        "Respond ONLY with valid raw JSON — no markdown, no code blocks.",
      ].join("\n");

      userPrompt = [
        `VIDEO TOPIC (with answers): "${videoTopic}"`,
        `BRAND COLOR: ${brandColor}`,
        `HIGHLIGHT COLOR: ${highlightColor || "#f5d800"}`,
        `SUBJECT: ${subjectInstruction}`,
        "",
        "Return the full plan:",
        "{",
        '  "needsMoreInfo": false,',
        '  "conceptTitle": "5-word evocative thumbnail concept name",',
        '  "ctrAnalysis": "2 sentences on why this will get high CTR",',
        '  "compositionStrategy": "1 sentence on visual layout",',
        '  "subjectPose": "A descriptive pose that incorporates a pointing hand gesture and a topic-relevant prop (e.g. \'right index finger pointing straight up, confident smiling expression, wearing a tailor\'s measuring tape around their neck and holding design blueprints\')",',
        '  "overlayConfig": {',
        '    "accentColor": "must use the exact HIGHLIGHT COLOR hex provided",',
        "    \"topBadge\": \"topic pill tag e.g. 'RGPV | MATHS-II' or null\",",
        '    "topBadgeColor": "badge background hex",',
        '    "headline1": "FIRST LINE — uppercase max 3 words (white text)",',
        '    "headline2": "SECOND LINE — uppercase max 3 words (accent color) or null",',
        '    "bannerText": "BOTTOM BANNER full string max 8 words or null",',
        '    "bannerAccentWord": "word to highlight yellow in banner or null",',
        '    "showAlertCard": true or false,',
        '    "alertTitle": "e.g. EXAM POSTPONED or null",',
        '    "alertBody": "1-2 sentence body or null",',
        '    "alertType": "error | success | info | warning",',
        '    "showDateCallout": true or false,',
        '    "dateText": "e.g. 1 AUG or null",',
        '    "dateIcon": "cross | check | fire | warning or null"',
        "  }",
        "}",
      ].join("\n");
    }

    const response = await fetch("https://api.deepseek.com/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: "deepseek-chat",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user",   content: userPrompt   },
        ],
        temperature: isSecondPass ? 0.85 : 0.3,
        response_format: { type: "json_object" },
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`AI Engine API failed: ${response.status} — ${errText}`);
    }

    const data = await response.json();
    let plan = JSON.parse(data.choices[0].message.content);

    // If DeepSeek needs more info from the user — return questions, don't generate yet
    if (plan.needsMoreInfo === true && Array.isArray(plan.questions) && plan.questions.length > 0) {
      return NextResponse.json({ success: true, needsMoreInfo: true, questions: plan.questions });
    }

    // First pass decided no clarification needed — immediately run second pass to build the full plan
    if (!isSecondPass && plan.needsMoreInfo === false) {
      const pass2System = [
        "You are the world's #1 YouTube thumbnail strategist for Indian education channels.",
        "",
        "Given ONLY the video topic, additional details, and brand color, you decide ALL creative elements.",
        "The final image will be fully generated by Kinetic AI — text, person, background, everything in one shot.",
        "",
        "Use your own judgment to decide which overlay elements genuinely fit the content.",
        "Think: what would a smart, experienced creator actually put on this thumbnail?",
        "A revision/lecture video needs a punchy headline — not an alert card or date callout.",
        "An exam postponement needs an alert card, a date callout, and an urgent banner.",
        "A result video needs a success card and excitement. Match the energy to the topic naturally.",
        "",
        "SUBJECT POSE RULES (CRITICAL):",
        "- Design a high-impact, highly relevant pose for the subject.",
        "- Ensure the subject is making a clear hand gesture (such as pointing their index finger straight up, pointing at the camera, or pointing at the headlines).",
        "- Crucially, specify a physical prop related to the topic that the subject is holding or wearing (e.g., for fashion: a tailor's measuring tape around their neck or holding design blueprints; for exams: holding a printed notice page or circular; for motivation: holding a trophy or book; for finance: holding a stack of charts).",
        "- The pose description in the plan should look like: 'right index finger pointing straight up, confident smiling expression, wearing a tailor's measuring tape around their neck and holding design blueprints'",
        "",
        "CRITICAL RULE: DO NOT HALLUCINATE, INVENT, OR ASSUME ANY FACTS OR DATES.",
        "- You now have all the explicit info from the creator.",
        "- Only use the details they provided.",
        "- Return the full plan with needsMoreInfo: false.",
        "",
        "TEXT RULES:",
        "- Headline: SHORT and PUNCHY — max 2-3 words per line",
        "- Use HINGLISH where it genuinely fits the topic tone",
        "- accentColor: bright high-contrast against the brand color (usually #f5d800 yellow)",
        "",
        "Respond ONLY with valid raw JSON — no markdown, no code blocks.",
      ].join("\n");

      const pass2User = [
        `VIDEO TOPIC (with answers): "${videoTopic}"`,
        `BRAND COLOR: ${brandColor}`,
        `HIGHLIGHT COLOR: ${highlightColor || "#f5d800"}`,
        `SUBJECT: ${subjectInstruction}`,
        "",
        "Return the full plan:",
        "{",
        '  "needsMoreInfo": false,',
        '  "conceptTitle": "5-word evocative thumbnail concept name",',
        '  "ctrAnalysis": "2 sentences on why this will get high CTR",',
        '  "compositionStrategy": "1 sentence on visual layout",',
        '  "subjectPose": "A descriptive pose that incorporates a pointing hand gesture and a topic-relevant prop (e.g. \'right index finger pointing straight up, confident smiling expression, wearing a tailor\'s measuring tape around their neck and holding design blueprints\')",',
        '  "overlayConfig": {',
        '    "accentColor": "must use the exact HIGHLIGHT COLOR hex provided",',
        "    \"topBadge\": \"topic pill tag e.g. 'RGPV | MATHS-II' or null\",",
        '    "topBadgeColor": "badge background hex",',
        '    "headline1": "FIRST LINE — uppercase max 3 words (white text)",',
        '    "headline2": "SECOND LINE — uppercase max 3 words (accent color) or null",',
        '    "bannerText": "BOTTOM BANNER full string max 8 words or null",',
        '    "bannerAccentWord": "word to highlight yellow in banner or null",',
        '    "showAlertCard": true or false,',
        '    "alertTitle": "e.g. EXAM POSTPONED or null",',
        '    "alertBody": "1-2 sentence body or null",',
        '    "alertType": "error | success | info | warning",',
        '    "showDateCallout": true or false,',
        '    "dateText": "e.g. 1 AUG or null",',
        '    "dateIcon": "cross | check | fire | warning or null"',
        "  }",
        "}",
      ].join("\n");

      const pass2Res = await fetch("https://api.deepseek.com/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": `Bearer ${apiKey}` },
        body: JSON.stringify({
          model: "deepseek-chat",
          messages: [
            { role: "system", content: pass2System },
            { role: "user",   content: pass2User   },
          ],
          temperature: 0.85,
          response_format: { type: "json_object" },
        }),
      });

      if (!pass2Res.ok) throw new Error(`AI Engine pass 2 failed: ${pass2Res.status}`);
      const pass2Data = await pass2Res.json();
      plan = JSON.parse(pass2Data.choices[0].message.content);
    }

    // Build the COMPLETE thumbnail prompt — text fully included, nothing added in browser
    plan.imagePrompt = buildCompleteThumbnailPrompt(plan, {
      videoTopic, brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode, creatorType,
    });

    return NextResponse.json({ success: true, needsMoreInfo: false, plan });

  } catch (error) {
    console.error("Plan Route Error:", error);
    return NextResponse.json({ success: false, error: "Planning failed. Please try again." }, { status: 500 });
  }
}

function buildCompleteThumbnailPrompt(plan, { videoTopic, brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode, creatorType }) {
  const oc     = plan.overlayConfig || {};
  const accent = highlightColor || oc.accentColor || "#f5d800";
  const dynamicPose = plan.subjectPose || "right index finger pointing straight up toward the sky (classic 'number one' gesture), confident smiling expression";

  const subjectNote = hasSubjectPhoto
    ? `MULTI-ANGLE FACE REFERENCE PROVIDED: The reference photo contains multi-angle facial reference shots (Front view, Left profile, Right profile) of the creator. Use these 3D facial angle references to reconstruct their exact face, facial structure, skin tone, and likeness with 100% precision. ` +
      (poseMode === "ai"
        ? `Give them the most expressive, dynamic pose based on this instruction: "${dynamicPose}". Dramatic cinematic rim lighting in the brand color.`
        : "Keep their exact pose from the reference photo(s). Dramatically enhance the lighting, styling, and background.")
    : `SUBJECT: Create a confident, expressive Indian educator/presenter. Pose instruction: "${dynamicPose}". Professional look, dramatic lighting.`;

  const textElements = [];

  if (oc.topBadge) {
    if (oc.topBadge.includes("|")) {
      const [p1, p2] = oc.topBadge.split("|").map(s => s.trim());
      textElements.push(
        "TOP-LEFT CORNER — Two pill-shaped label badges side by side:\n" +
        "  Badge 1: Bold white text \"" + p1 + "\" on solid " + oc.topBadgeColor + " background, rounded corners\n" +
        "  Badge 2: Bold black text \"" + p2 + "\" on solid white background, rounded corners"
      );
    } else {
      textElements.push(
        "TOP-LEFT CORNER — Pill badge: Bold white text \"" + oc.topBadge + "\" on solid " + oc.topBadgeColor + " background, rounded corners"
      );
    }
  }

  if (oc.headline1 || oc.headline2) {
    const h1 = oc.headline1 ? ("\"" + oc.headline1.toUpperCase() + "\"") : null;
    const h2 = oc.headline2 ? ("\"" + oc.headline2.toUpperCase() + "\"") : null;
    textElements.push(
      "MAIN HEADLINE — Left-center of frame, vertically centred, stacked:\n" +
      (h1 ? ("  Line 1: " + h1 + " — massive Impact/heavy condensed font, pure WHITE, extremely large, strong text-shadow\n") : "") +
      (h2 ? ("  Line 2: " + h2 + " — same massive size, ITALIC, color " + accent + " (bright yellow), strong text-shadow\n") : "") +
      "  Both lines left-aligned"
    );
  }

  if (oc.showAlertCard && oc.alertTitle) {
    const alertBg = oc.alertType === "error" ? "#dc2626" : oc.alertType === "success" ? "#16a34a" : oc.alertType === "warning" ? "#d97706" : "#1d4ed8";
    textElements.push(
      "TOP-RIGHT CORNER — Official-looking white notice card:\n" +
      "  - Small grey header: \"Examination Notice\"\n" +
      "  - Coloured title bar (" + alertBg + "): bold white text \"" + oc.alertTitle.toUpperCase() + "\"\n" +
      "  - Body text: \"" + (oc.alertBody || "").slice(0, 100) + "\"\n" +
      "  Style: like an official WhatsApp forwarded notice or university circular"
    );
  }

  if (oc.showDateCallout && oc.dateText) {
    const iconMap = { cross: "bold red X", check: "green checkmark", fire: "fire emoji", warning: "warning symbol" };
    const iconDesc = iconMap[oc.dateIcon] || "warning symbol";
    textElements.push(
      "CENTER AREA — Calendar-style white popup:\n" +
      "  - Red top band (like a calendar header)\n" +
      "  - Large bold date text: \"" + oc.dateText.toUpperCase() + "\"\n" +
      "  - A circular " + iconDesc + " badge at bottom-right corner of the calendar"
    );
  }

  if (oc.bannerText) {
    const upper      = oc.bannerText.toUpperCase();
    const accentWord = oc.bannerAccentWord ? oc.bannerAccentWord.toUpperCase() : null;
    const bannerDesc = accentWord
      ? ("\"" + upper + "\" — the word \"" + accentWord + "\" in " + accent + " (bright yellow), the rest in white")
      : ("\"" + upper + "\" in white");
    textElements.push(
      "FULL-WIDTH BOTTOM BANNER STRIP (spans entire width):\n" +
      "  - Solid dark background: " + brandColor + " or very dark navy\n" +
      "  - A thin " + accent + " accent line at the top of the strip\n" +
      "  - Impact/condensed bold font: " + bannerDesc + "\n" +
      (oc.dateIcon === "cross" ? "  - A prominent red X circle icon on the left before the text\n" : "") +
      "  Text centred vertically in the strip, large and readable"
    );
  }

  const textSection = textElements.length > 0
    ? textElements.map((el, i) => ((i + 1) + ". " + el)).join("\n\n")
    : "Bold impactful headline on the left side in white Impact font with accent-colored supporting text below";

  if (creatorType === "vlogs") {
    return (
      "Generate a COMPLETE, cinematic Vlog YouTube thumbnail image. Every element described below must appear " +
      "in the final image — this is the finished, ready-to-upload thumbnail, not a background.\n\n" +
      "REFERENCE STYLE: Top Indian & Global Lifestyle Vlogger thumbnails (Flying Beast, Sourav Joshi Vlogs). " +
      "Candid storytelling, ultra-expressive presenter, warm cinematic lighting, bold headline text.\n\n" +
      "FORMAT: 16:9 landscape (2560x1440)\n\n" +
      "VLOG STORY/TOPIC: " + (videoTopic || "") + "\n" +
      "This is what the thumbnail must visually represent. The background scene, any props the subject holds, any visible objects, and the overall visual metaphor " +
      "must all clearly communicate this specific vlog story at a glance. Include realistic props matching the story (e.g. vlog camera on gorilla pod, suitcases, car keys, gift wrapping).\n\n" +
      "LAYOUT ZONES:\n" +
      "- LEFT/CENTER 50% — Expressive Vlogger / Subjects (with warm, natural rim lighting)\n" +
      "- RIGHT / TOP — High-contrast stacked headline text and location pill badge\n" +
      "- BACKGROUND — Real-world immersive location (airport lounge, scenic drive, home lounge) with 35mm bokeh\n\n" +
      "SUBJECT:\n" + subjectNote + "\n\n" +
      "BACKGROUND:\n" +
      "Cinematic real-world environment. " + brandColor + " is used as warm atmospheric accent and rim lighting on the subject. Shallow depth of field.\n\n" +
      "TEXT AND OVERLAY ELEMENTS (render ALL of these with sharp, crisp text):\n" +
      textSection + "\n\n" +
      "TYPOGRAPHY RULES:\n" +
      "- Headlines: Impact or ultra-bold condensed sans-serif, ALL CAPS, 2 lines max\n" +
      "- Badges/pills: Bold rounded location or series pill\n" +
      "- All text: 100% correctly spelled, sharp edges, strong drop-shadow for legibility over real-world backgrounds\n\n" +
      "ANATOMY RULES (CRITICAL):\n" +
      "- The subject MUST have exactly two natural arms and hands.\n" +
      "- Hands must be perfectly formed, anatomically correct, and attached naturally to the body.\n\n" +
      "COLOR PALETTE:\n" +
      "- Brand/dominant: " + brandColor + "\n" +
      "- Accent/highlight: " + accent + "\n" +
      "- Primary text: #FFFFFF (white)\n" +
      "- Secondary text: " + accent + "\n\n" +
      "QUALITY: Photorealistic, 4K magazine-cover grade, hyper-engaging. " +
      "Make it visually irresistible so viewers instantly want to click and see what happened."
    );
  }
  if (creatorType === "gaming") {
    return (
      "Generate a COMPLETE, explosive Gaming YouTube thumbnail image. Every element described below must appear " +
      "in the final image — this is the finished, ready-to-upload thumbnail, not a background.\n\n" +
      "REFERENCE STYLE: Top-tier Esports & Gaming Creator thumbnails (Techno Gamerz, Total Gaming, CarryMinati, MrBeast Gaming). " +
      "Hyper-expressive gamer reaction, 3D game environment, volumetric lighting, epic particle effects, high-CTR 3D text.\n\n" +
      "FORMAT: 16:9 landscape (2560x1440)\n\n" +
      "GAMING TOPIC / CHALLENGE: " + (videoTopic || "") + "\n" +
      "This is what the thumbnail must visually represent. The game world, props, and environment must immediately tell the story " +
      "(e.g. holding a glowing game controller or keyboard, surrounded by loot crates, explosive battle royale background, or rare secret room).\n\n" +
      "COLOR & LIGHTING (DYNAMIC ADAPTIVE):\n" +
      "Do NOT restrict to a single color. Dynamically choose the best high-contrast color palette matching the specific game world " +
      "(e.g., glowing neon cyan, fiery orange/yellow sparks, intense purple energy, or dark cinematic moody atmospheric lighting). " +
      "Dramatic volumetric light rays and rim lighting on the subject.\n\n" +
      "LAYOUT ZONES:\n" +
      "- LEFT 45% — Gamer/Presenter wearing a gaming headset with extreme, expressive facial reaction (jaw-dropped shock, shouting victory, or intense focus).\n" +
      "- RIGHT 55% — Immersive 3D game action environment with cinematic depth of field, embers, and action effects.\n" +
      "- OVERLAYS — High-contrast 3D headline text and game badge overlay.\n\n" +
      "SUBJECT:\n" + subjectNote + "\n\n" +
      "TEXT AND OVERLAY ELEMENTS (render ALL of these with sharp, crisp text):\n" +
      textSection + "\n\n" +
      "TYPOGRAPHY RULES:\n" +
      "- Headlines: Ultra-bold Impact font with 3D bevel effect, ALL CAPS, short intriguing 2-line phrase (e.g. 'INSANE CLUTCH!' or 'SECRET ROOM!'). Strong text shadow and glowing border for perfect readability.\n" +
      "- Badges: Game rank emblem or 1v4 survivor pill tag.\n" +
      "- All text: 100% correctly spelled, sharp 3D edges, glowing contrast over busy game backgrounds.\n\n" +
      "ANATOMY RULES (CRITICAL):\n" +
      "- The subject MUST have exactly two natural arms and hands.\n" +
      "- Hands must be perfectly formed, anatomically correct, and attached naturally to the body.\n\n" +
      "QUALITY: Photorealistic, 4K render quality, hyper-engaging, maximum CTR. Make it visually thrilling so gamers scroll-stoppingly click."
    );
  }

  return (
    "Generate a COMPLETE, professional YouTube thumbnail image. Every element described below must appear " +
    "in the final image — this is the finished, ready-to-upload thumbnail, not a background.\n\n" +
    "REFERENCE STYLE: Top Indian YouTube education/news channels (Physics Wallah, Vedantu, Unacademy). " +
    "Bold typography, dramatic backgrounds, expressive presenter, coloured text banners, official notice card overlays. " +
    "Ultra high production value.\n\n" +
    "FORMAT: 16:9 landscape (1280x720)\n\n" +
    "VIDEO TOPIC: " + (videoTopic || "") + "\n" +
    "This is what the thumbnail must visually represent. " +
    "The background scene, any props the subject holds, any visible objects, and the overall visual metaphor " +
    "must all clearly communicate this specific topic at a glance. " +
    "For example: if the topic is Engineering Drawing, include drafting tools, T-squares, blueprints, technical sheets. " +
    "If Maths, include equations on a board. If History, include relevant artefacts. " +
    "The subject matter must be UNMISTAKABLY CLEAR from the visuals alone.\n\n" +
    "LAYOUT ZONES:\n" +
    "- LEFT 40% — Subject / Person (with dramatic lighting)\n" +
    "- CENTER — Supporting graphic elements (date callout if any)\n" +
    "- RIGHT area + OVERLAYS — Text elements\n\n" +
    "SUBJECT:\n" + subjectNote + "\n\n" +
    "BACKGROUND:\n" +
    "Cinematic, dramatic environment. " + brandColor + " is the dominant atmospheric color — used as rim lighting " +
    "on the subject, ambient glow, and color accent in the background. Dark and moody. Depth of field.\n\n" +
    "TEXT AND OVERLAY ELEMENTS (render ALL of these with sharp, crisp text):\n" +
    textSection + "\n\n" +
    "TYPOGRAPHY RULES:\n" +
    "- Headlines: Impact or ultra-bold condensed sans-serif, ALL CAPS, very large\n" +
    "- Badges/pills: Bold rounded sans-serif\n" +
    "- Banner: Impact/condensed, ALL CAPS\n" +
    "- All text: 100% correctly spelled, sharp edges, strong drop-shadow for legibility\n\n" +
    "ANATOMY RULES (CRITICAL):\n" +
    "- The subject MUST have exactly two natural arms and hands.\n" +
    "- Hands must be perfectly formed, anatomically correct, and attached naturally to the body.\n" +
    "- STRICTLY NO extra floating hands, NO extra fingers, and NO distorted limbs. Keep hands out of the frame if they cannot be rendered perfectly.\n\n" +
    "COLOR PALETTE:\n" +
    "- Brand/dominant: " + brandColor + "\n" +
    "- Accent/highlight: " + accent + "\n" +
    "- Primary text: #FFFFFF (white)\n" +
    "- Secondary text: " + accent + "\n\n" +
    "QUALITY: Photorealistic, ultra-sharp, magazine-cover grade. " +
    "The thumbnail must look like it belongs on a channel with 5M+ subscribers. " +
    "Make it VISUALLY STUNNING — the kind of image that makes someone stop mid-scroll and immediately click."
  );
}

/* ── Smart fallback (no API key) ──────────────────────────────────── */
function buildFallbackPlan({ videoTopic, brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode }, forceFull = false) {
  const isSecondPass = forceFull || videoTopic.includes("Additional details provided by creator:");

  if (!isSecondPass) {
    return {
      needsMoreInfo: true,
      questions: [
        {
          question: "Are there any specific dates or numbers to include in the design?",
          options: ["No dates", "Today's date", "Tomorrow", "Other (please specify)"]
        },
        {
          question: "What is the exact short text/headline you want to highlight?",
          options: ["Let AI decide", "Keep it minimal", "Match the video title", "Other (please specify)"]
        }
      ]
    };
  }

  const t           = (videoTopic || "").toLowerCase();
  const hasExam     = t.includes("exam") || t.includes("paper") || t.includes("test");
  const hasPostpone = t.includes("postpone") || t.includes("cancel") || t.includes("change") || t.includes("update");
  const hasResult   = t.includes("result") || t.includes("merit") || t.includes("rank");
  const dateMatch   = t.match(/(\d{1,2})\s*(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/i);
  const dateText    = dateMatch ? (dateMatch[1] + " " + dateMatch[2].toUpperCase()) : "SOON";

  let headline1 = "BIG", headline2 = "UPDATE!";
  let bannerText = "YEH VIDEO ZAROOR DEKHO!", bannerAccentWord = "ZAROOR";
  let alertTitle = null, alertBody = null, alertType = "info";
  let showAlertCard = false, showDateCallout = false, dateIcon = "warning";
  let topBadge = null;

  const isAnnouncement = hasExam && hasPostpone;
  const isResult       = hasResult;

  if (isAnnouncement) {
    headline1 = "BIGGEST"; headline2 = "CHANGE!";
    bannerText = "AB EXAM DATE CHANGE HO GAYI!"; bannerAccentWord = "EXAM DATE";
    showAlertCard = true; alertTitle = "EXAM POSTPONED";
    alertBody = videoTopic.slice(0, 120); alertType = "error";
    showDateCallout = !!dateMatch; dateIcon = "cross"; topBadge = "EXAM UPDATE";
  } else if (isResult) {
    headline1 = "RESULT"; headline2 = "OUT!";
    bannerText = "CHECK YOUR RESULT ABHI!"; bannerAccentWord = "RESULT";
    showAlertCard = true; alertTitle = "RESULT DECLARED";
    alertBody = videoTopic.slice(0, 100); alertType = "success";
    topBadge = "RESULT 2024";
  } else {
    headline1 = "IMP"; headline2 = "TOPICS";
    bannerText = null; bannerAccentWord = null;
    showAlertCard = false; showDateCallout = false;
    topBadge = "MUST WATCH";
  }

  const overlayConfig = {
    accentColor: highlightColor || "#f5d800", topBadge, topBadgeColor: brandColor,
    headline1, headline2, bannerText, bannerAccentWord,
    showAlertCard, alertTitle, alertBody, alertType,
    showDateCallout, dateText, dateIcon,
  };

  const plan = {
    conceptTitle: isAnnouncement ? "High-Impact Breaking Announcement" : isResult ? "Result Reveal Thumbnail" : "High-Energy Lecture Thumbnail",
    ctrAnalysis: isAnnouncement
      ? "This topic carries high urgency — triggering immediate FOMO. Bold Hinglish text + official notice card creates maximum attention in under 1 second."
      : "Bold, punchy headline with energetic subject creates an instant watch reaction from students scrolling through their feed.",
    compositionStrategy: "Subject LEFT with expressive pose. Text RIGHT. Dramatic brand-color lighting. Clean, impactful layout.",
    subjectPose: isAnnouncement ? "looking shocked with hands on head" : isResult ? "celebrating with fist pump" : "pointing at the text confidently",
    overlayConfig,
    imagePrompt: "",
  };

  plan.imagePrompt = buildCompleteThumbnailPrompt(plan, { videoTopic, brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode });
  return plan;
}
