import { NextResponse } from "next/server";
import { getSessionUser } from "../../../lib/auth";
import { checkRateLimit } from "../../../lib/rate-limit";

/* ────────────────────────────────────────────────────────────────
   AI decides EVERYTHING from minimal input.
   Kinetic AI then generates the COMPLETE final thumbnail —
   background + person + all text baked into one image.
   ──────────────────────────────────────────────────────────────── */

export async function POST(request) {
  try {
    const rateLimit = checkRateLimit(request, "plan", 30, 60 * 60 * 1000);
    if (!rateLimit.allowed) return NextResponse.json({ success: false, error: "Planning limit reached. Please try again later." }, { status: 429, headers: { "Retry-After": String(rateLimit.retryAfter) } });
    const user = await getSessionUser();
    if (!user) {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { videoTopic, brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode } = body;
    if (typeof videoTopic !== "string" || videoTopic.trim().length === 0 || videoTopic.length > 8_000) {
      return NextResponse.json({ success: false, error: "Video topic must be between 1 and 8,000 characters." }, { status: 400 });
    }

    const apiKey = process.env.DEEPSEEK_API_KEY;

    /* ── Mock fallback (no key) ─────────────────────────────────── */
    if (!apiKey) {
      console.log("DeepSeek key missing — returning smart fallback plan");
      await new Promise(r => setTimeout(r, 1400));
      const plan = buildFallbackPlan({ videoTopic, brandColor, highlightColor, hasSubjectPhoto, poseMode });
      return NextResponse.json({ success: true, plan, isMock: true });
    }

    /* ── Live DeepSeek call ─────────────────────────────────────── */
    const subjectInstruction = hasSubjectPhoto
      ? `Real reference photo(s) of ${subjectCount > 1 ? subjectCount + " creators" : "the creator"} will be sent to the image model. Pose mode: "${poseMode}" — ${
          poseMode === "ai"
            ? "choose the most impactful pose (pointing up, shocked, excited, authoritative)"
            : "keep their exact pose from the reference photo(s)"
        }.`
      : "No subject photo. Image model will create a compelling Indian educator/presenter character.";

    const isSecondPass = videoTopic.includes("Additional details provided by creator:");

    let systemPrompt, userPrompt;

    if (!isSecondPass) {
      // Mandatory First Pass: Ask Questions
      systemPrompt = [
        "You are an elite YouTube thumbnail strategist.",
        "Your task is to interview the creator to gather EVERY detail needed before designing.",
        "DO NOT assume or invent any text, dates, or concepts.",
        "You MUST ask exactly 3 to 4 specific questions based on their topic to gather all possible details (e.g., exact text for the thumbnail, specific dates, visual metaphors, preferred layout, or tone).",
        "For each question, provide 3 to 4 likely multiple-choice options for the creator to choose from. One option should always be 'Other (please specify)'.",
        "Respond ONLY with valid raw JSON in the following format:",
        '{ "needsMoreInfo": true, "questions": [ { "question": "Question 1?", "options": ["Option 1", "Option 2", "Other (please specify)"] } ] }',
      ].join("\n");

      userPrompt = `VIDEO TOPIC: "${videoTopic}"\n\nAnalyze the topic and generate the mandatory clarification questions now.`;
    } else {
          // Second Pass: Generate Full Plan
      systemPrompt = [
        "You are the world's #1 YouTube thumbnail strategist for Indian education channels.",
        "",
        "Given the video topic, additional details, and brand color, you decide ALL creative elements.",
        "The final image will be fully generated by Kinetic AI — text, person, background, everything in one shot.",
        "",
        "Use your own judgment to decide which overlay elements genuinely fit the content.",
        "Think: what would a smart, experienced creator actually put on this thumbnail?",
        "A revision/lecture video needs a punchy headline — not an alert card or date callout.",
        "An exam postponement needs an alert card, a date callout, and an urgent banner.",
        "A result video needs a success card and excitement. Match the energy to the topic naturally.",
        "",
        "CRITICAL RULE: DO NOT HALLUCINATE, INVENT, OR ASSUME ANY FACTS OR DATES.",
        "- You now have all the explicit info from the creator.",
        "- Only use the details they provided.",
        "- Return the full plan with needsMoreInfo: false.",
        "",
        "TEXT RULES:",
        "- Headline: SHORT and PUNCHY — max 2-3 words per line",
        "- accentColor: bright high-contrast against the brand color (usually #f5d800 yellow)",
        "",
        "Respond ONLY with valid raw JSON — no markdown, no code blocks.",
      ].join("\n");

      userPrompt = [
        `VIDEO TOPIC (with creator's answers): "${videoTopic}"`,
        `BRAND COLOR: ${brandColor}`,
        `HIGHLIGHT COLOR: ${highlightColor || "#f5d800"}`,
        `SUBJECT: ${subjectInstruction}`,
        "",
        "Return the full plan:",
        "{",
        '  "needsMoreInfo": false,',
        '  "conceptTitle": "5-word evocative thumbnail concept name",',
        '  "ctrAnalysis": "2 sentences on why this will get high CTR",',
        '  "compositionStrategy": "1 sentence on visual layout",',
        '  "subjectPose": "A descriptive pose based ONLY on the emotion of the topic (e.g. \'looking stressed with hands on head\', \'holding up a paper victoriously\', \'looking confused\'). Do NOT default to pointing upward unless it fits.",',
        '  "overlayConfig": {',
        '    "accentColor": "must use the exact HIGHLIGHT COLOR hex provided",',
        "    \"topBadge\": \"topic pill tag e.g. 'RGPV | MATHS-II' or null\",",
        '    "topBadgeColor": "badge background hex",',
        '    "headline1": "FIRST LINE — uppercase max 3 words (white text)",',
        '    "headline2": "SECOND LINE — uppercase max 3 words (accent color) or null",',
        '    "bannerText": "BOTTOM BANNER full string max 8 words or null",',
        '    "bannerAccentWord": "word to highlight yellow in banner or null",',
        '    "showAlertCard": true or false,',
        '    "alertTitle": "e.g. EXAM POSTPONED or null",',
        '    "alertBody": "1-2 sentence body or null",',
        '    "alertType": "error | success | info | warning",',
        '    "showDateCallout": true or false,',
        '    "dateText": "e.g. 1 AUG or null",',
        '    "dateIcon": "cross | check | fire | warning or null"',
        "  }",
        "}",
      ].filter(Boolean).join("\n");
    }

    const response = await fetch("https://api.deepseek.com/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: "deepseek-chat",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user",   content: userPrompt   },
        ],
        temperature: 0.82,
        response_format: { type: "json_object" },
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`AI Engine API failed: ${response.status} — ${errText}`);
    }

    const data = await response.json();
    const plan = JSON.parse(data.choices[0].message.content);

    // If DeepSeek needs more info from the user — return questions, don't generate yet
    if (plan.needsMoreInfo === true && Array.isArray(plan.questions) && plan.questions.length > 0) {
      return NextResponse.json({ success: true, needsMoreInfo: true, questions: plan.questions });
    }

    // Build the COMPLETE thumbnail prompt — text fully included, nothing added in browser
    plan.imagePrompt = buildCompleteThumbnailPrompt(plan, {
      brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode, videoTopic,
    });

    return NextResponse.json({ success: true, needsMoreInfo: false, plan });

  } catch (error) {
    console.error("Plan Route Error:", error);
    return NextResponse.json({ success: false, error: "Planning failed. Please try again." }, { status: 500 });
  }
}

/* ══════════════════════════════════════════════════════════════════
   Build the COMPLETE final thumbnail prompt for Kinetic AI.
   ALL text, badges, banners, overlays are specified here so they
   get BAKED INTO the generated image — nothing added in the browser.
   ══════════════════════════════════════════════════════════════════ */
function buildCompleteThumbnailPrompt(plan, { brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode, videoTopic }) {
  const oc     = plan.overlayConfig || {};
  const accent = highlightColor || oc.accentColor || "#f5d800";
  const dynamicPose = plan.subjectPose || "pointing upward confidently or open-mouth shock";

  const subjectNote = hasSubjectPhoto
    ? `SUBJECT PHOTO(S) PROVIDED: Use the exact face, skin tone, and likeness for the ${subjectCount} person/people provided — preserve their identity completely. ` +
      (poseMode === "ai"
        ? `Give them the most expressive, dynamic pose based on this instruction: "${dynamicPose}". Dramatic cinematic rim lighting in the brand color.`
        : "Keep their exact pose from the reference photo(s). Dramatically enhance the lighting, styling, and background.")
    : `SUBJECT: Create a confident, expressive Indian educator/presenter. Pose instruction: "${dynamicPose}". Professional look, dramatic lighting.`;

  const textElements = [];

  if (oc.topBadge) {
    if (oc.topBadge.includes("|")) {
      const [p1, p2] = oc.topBadge.split("|").map(s => s.trim());
      textElements.push(
        "TOP-LEFT CORNER — Two pill-shaped label badges side by side:\n" +
        "  Badge 1: Bold white text \"" + p1 + "\" on solid " + oc.topBadgeColor + " background, rounded corners\n" +
        "  Badge 2: Bold black text \"" + p2 + "\" on solid white background, rounded corners"
      );
    } else {
      textElements.push(
        "TOP-LEFT CORNER — Pill badge: Bold white text \"" + oc.topBadge + "\" on solid " + oc.topBadgeColor + " background, rounded corners"
      );
    }
  }

  if (oc.headline1 || oc.headline2) {
    const h1 = oc.headline1 ? ("\"" + oc.headline1.toUpperCase() + "\"") : null;
    const h2 = oc.headline2 ? ("\"" + oc.headline2.toUpperCase() + "\"") : null;
    textElements.push(
      "MAIN HEADLINE — Left-center of frame, vertically centred, stacked:\n" +
      (h1 ? ("  Line 1: " + h1 + " — massive Impact/heavy condensed font, pure WHITE, extremely large, strong text-shadow\n") : "") +
      (h2 ? ("  Line 2: " + h2 + " — same massive size, ITALIC, color " + accent + ", strong text-shadow\n") : "") +
      "  Both lines left-aligned"
    );
  }

  if (oc.showAlertCard && oc.alertTitle) {
    const alertBg = oc.alertType === "error" ? "#dc2626" : oc.alertType === "success" ? "#16a34a" : oc.alertType === "warning" ? "#d97706" : "#1d4ed8";
    textElements.push(
      "TOP-RIGHT CORNER — Official-looking white notice card:\n" +
      "  - Small grey header: \"Examination Notice\"\n" +
      "  - Coloured title bar (" + alertBg + "): bold white text \"" + oc.alertTitle.toUpperCase() + "\"\n" +
      "  - Body text: \"" + (oc.alertBody || "").slice(0, 100) + "\"\n" +
      "  Style: like an official WhatsApp forwarded notice or university circular"
    );
  }

  if (oc.showDateCallout && oc.dateText) {
    const iconMap = { cross: "bold red X", check: "green checkmark", fire: "fire emoji", warning: "warning symbol" };
    const iconDesc = iconMap[oc.dateIcon] || "warning symbol";
    textElements.push(
      "CENTER AREA — Calendar-style white popup:\n" +
      "  - Red top band (like a calendar header)\n" +
      "  - Large bold date text: \"" + oc.dateText.toUpperCase() + "\"\n" +
      "  - A circular " + iconDesc + " badge at bottom-right corner of the calendar"
    );
  }

  if (oc.bannerText) {
    const upper      = oc.bannerText.toUpperCase();
    const accentWord = oc.bannerAccentWord ? oc.bannerAccentWord.toUpperCase() : null;
    const bannerDesc = accentWord
      ? ("\"" + upper + "\" — the word \"" + accentWord + "\" in " + accent + ", the rest in white")
      : ("\"" + upper + "\" in white");
    textElements.push(
      "FULL-WIDTH BOTTOM BANNER STRIP (spans entire width):\n" +
      "  - Solid dark background: " + brandColor + " or very dark navy\n" +
      "  - A thin " + accent + " accent line at the top of the strip\n" +
      "  - Impact/condensed bold font: " + bannerDesc + "\n" +
      (oc.dateIcon === "cross" ? "  - A prominent red X circle icon on the left before the text\n" : "") +
      "  Text centred vertically in the strip, large and readable"
    );
  }

  const textSection = textElements.length > 0
    ? textElements.map((el, i) => ((i + 1) + ". " + el)).join("\n\n")
    : "Bold impactful headline on the left side in white Impact font with accent-colored supporting text below";

  return (
    "Generate a COMPLETE, professional YouTube thumbnail image. Every element described below must appear " +
    "in the final image — this is the finished, ready-to-upload thumbnail, not a background.\n\n" +
    "REFERENCE STYLE: Top Indian YouTube education/news channels (Physics Wallah, Vedantu, Unacademy). " +
    "Bold typography, dramatic backgrounds, expressive presenter, coloured text banners, official notice card overlays. " +
    "Ultra high production value.\n\n" +
    "FORMAT: 16:9 landscape (1280x720)\n\n" +
    "LAYOUT ZONES:\n" +
    "- LEFT 40% — Subject / Person (with dramatic lighting)\n" +
    "- CENTER — Supporting graphic elements (date callout if any)\n" +
    "- RIGHT area + OVERLAYS — Text elements\n\n" +
    "SUBJECT:\n" + subjectNote + "\n\n" +
    "BACKGROUND:\n" +
    "Cinematic, dramatic environment. " + brandColor + " is the dominant atmospheric color — used as rim lighting " +
    "on the subject, ambient glow, and color accent in the background. Dark and moody. Depth of field.\n\n" +
    "TEXT AND OVERLAY ELEMENTS (render ALL of these with sharp, crisp text):\n" +
    textSection + "\n\n" +
    "TYPOGRAPHY RULES:\n" +
    "- Headlines: Impact or ultra-bold condensed sans-serif, ALL CAPS, very large\n" +
    "- Badges/pills: Bold rounded sans-serif\n" +
    "- Banner: Impact/condensed, ALL CAPS\n" +
    "- All text: 100% correctly spelled, sharp edges, strong drop-shadow for legibility\n\n" +
    "ANATOMY RULES (CRITICAL):\n" +
    "- The subject MUST have exactly two natural arms and hands.\n" +
    "- Hands must be perfectly formed, anatomically correct, and attached naturally to the body.\n" +
    "- STRICTLY NO extra floating hands, NO extra fingers, and NO distorted limbs. Keep hands out of the frame if they cannot be rendered perfectly.\n\n" +
    "COLOR PALETTE:\n" +
    "- Brand/dominant: " + brandColor + "\n" +
    "- Accent/highlight: " + accent + "\n" +
    "- Primary text: #FFFFFF (white)\n" +
    "- Secondary text: " + accent + "\n\n" +
    "QUALITY: Photorealistic, ultra-sharp, magazine-cover grade. " +
    "The thumbnail must look like it belongs on a channel with 5M+ subscribers. " +
    "Make it VISUALLY STUNNING — the kind of image that makes someone stop mid-scroll and immediately click."
  );
}

/* ── Smart fallback (no API key) ──────────────────────────────────── */
function buildFallbackPlan({ videoTopic, brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode }) {
  const isSecondPass = videoTopic.includes("Additional details provided by creator:");

  if (!isSecondPass) {
    return {
      needsMoreInfo: true,
      questions: [
        {
          question: "What is the exact text you want on the thumbnail?",
          options: ["Let AI decide", "Keep it minimal", "Match the video title", "Other (please specify)"]
        },
        {
          question: "Are there any specific dates or numbers to include?",
          options: ["No dates", "Today's date", "Tomorrow", "Other (please specify)"]
        },
        {
          question: "What specific subject pose or emotion would you prefer?",
          options: ["Let AI decide", "Looking shocked", "Looking happy/victorious", "Other (please specify)"]
        }
      ]
    };
  }

  const t           = (videoTopic || "").toLowerCase();
  const hasExam     = t.includes("exam") || t.includes("paper") || t.includes("test");
  const hasPostpone = t.includes("postpone") || t.includes("cancel") || t.includes("change") || t.includes("update");
  const hasResult   = t.includes("result") || t.includes("merit") || t.includes("rank");
  const dateMatch   = t.match(/(\d{1,2})\s*(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/i);
  const dateText    = dateMatch ? (dateMatch[1] + " " + dateMatch[2].toUpperCase()) : "SOON";

  let headline1 = "BIG", headline2 = "UPDATE!";
  let bannerText = "YEH VIDEO ZAROOR DEKHO!", bannerAccentWord = "ZAROOR";
  let alertTitle = null, alertBody = null, alertType = "info";
  let showAlertCard = false, showDateCallout = false, dateIcon = "warning";
  let topBadge = null;

  const isAnnouncement = hasExam && hasPostpone;
  const isResult       = hasResult;

  if (isAnnouncement) {
    headline1 = "BIGGEST"; headline2 = "CHANGE!";
    bannerText = "AB EXAM DATE CHANGE HO GAYI!"; bannerAccentWord = "EXAM DATE";
    showAlertCard = true; alertTitle = "EXAM POSTPONED";
    alertBody = videoTopic.slice(0, 120); alertType = "error";
    showDateCallout = !!dateMatch; dateIcon = "cross"; topBadge = "EXAM UPDATE";
  } else if (isResult) {
    headline1 = "RESULT"; headline2 = "OUT!";
    bannerText = "CHECK YOUR RESULT ABHI!"; bannerAccentWord = "RESULT";
    showAlertCard = true; alertTitle = "RESULT DECLARED";
    alertBody = videoTopic.slice(0, 100); alertType = "success";
    topBadge = "RESULT 2024";
  } else {
    headline1 = "IMP"; headline2 = "TOPICS";
    bannerText = null; bannerAccentWord = null;
    showAlertCard = false; showDateCallout = false;
    topBadge = "MUST WATCH";
  }

  const overlayConfig = {
    accentColor: highlightColor || "#f5d800", topBadge, topBadgeColor: brandColor,
    headline1, headline2, bannerText, bannerAccentWord,
    showAlertCard, alertTitle, alertBody, alertType,
    showDateCallout, dateText, dateIcon,
  };

  const plan = {
    conceptTitle: isAnnouncement ? "High-Impact Breaking Announcement" : isResult ? "Result Reveal Thumbnail" : "High-Energy Lecture Thumbnail",
    ctrAnalysis: isAnnouncement
      ? "This topic carries high urgency — triggering immediate FOMO. Bold Hinglish text + official notice card creates maximum attention in under 1 second."
      : "Bold, punchy headline with energetic subject creates an instant watch reaction from students scrolling through their feed.",
    compositionStrategy: "Subject LEFT with expressive pose. Text RIGHT. Dramatic brand-color lighting. Clean, impactful layout.",
    subjectPose: isAnnouncement ? "looking shocked with hands on head" : isResult ? "celebrating with fist pump" : "pointing at the text confidently",
    overlayConfig,
    imagePrompt: "",
  };

  plan.imagePrompt = buildCompleteThumbnailPrompt(plan, { brandColor, highlightColor, hasSubjectPhoto, subjectCount, poseMode });
  return plan;
}
